name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  PROJECT_ID: gcp-5ann01-sbx-devopspoc
  SERVICE_ACCOUNT_EMAIL: github-actions-test@gcp-5ann01-sbx-devopspoc.iam.gserviceaccount.com
  REGION: us-central1
  REPO: hello-repo2

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          token_format: access_token
          workload_identity_provider: 'projects/937980401410/locations/global/workloadIdentityPools/cicd-pool/providers/cicd-provider'
          service_account: ${{ env.SERVICE_ACCOUNT_EMAIL }}

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Build and Deploy to Cloud Run
        run: |
          gcloud builds submit --tag $REGION-docker.pkg.dev/$PROJECT_ID/$REPO/hello-app2 \
            --service-account projects/$PROJECT_ID/serviceAccounts/$SERVICE_ACCOUNT_EMAIL \
            --gcs-log-dir gs://gcp-5ann01-sbx-devopspoc_cloudbuild/
          gcloud run deploy hello-app2 \
            --image $REGION-docker.pkg.dev/$PROJECT_ID/$REPO/hello-app2 \
            --platform managed \
            --region $REGION \
            --allow-unauthenticated
